### ISSUE TITLE
Remove Java + THREDDS

### ISSUE THREAD

**Issue by htmlboss** [DFO-Ocean-Navigator/Navigator-Installer#14]
Now that we've dumped THREDDS from the Navigator backend stack, we can remove Java + THREDDS from the installer script.

The relevant code could be moved to a separate script for archiving purposes.

@dwayne-hart

**Comment by wyj880220** [comment]
if remove the THREDDS from the Navigator，how can i install the system and run，wish your reply

**Comment by dwayne-hart** [comment]
This request has been acted upon and a new installation method implemented.
