### ISSUE TITLE
Update install instructions

### ISSUE THREAD

**Issue by jmunroe** [DFO-Ocean-Navigator/Navigator-Installer#23]
I just was going through the install instructions again on as given in the README.md on clean Ubuntu 18.04 LTS install.

At the `yarn install` step got the following error:

> error chalk@4.1.0: The engine "node" is incompatible with this module. Expected version ">=10". Got "8.16.0"
> error Found incompatible module.

Do we need to update the instructions to require node >= 10?

**Comment by dwayne-hart** [comment]
This should be resolved with [pull request 24](https://github.com/DFO-Ocean-Navigator/Navigator-Installer/pull/24). node was updated from v8.16.0 to v12.18.4.

**Comment by jmunroe** [comment]
Thanks.  Lots of changes in that PR.    It looks though that now the miniconda install has the path "/mnt/ramdisk/tools/" baked in (instead of the the expected "/home/buildadm/tools") which is causing things to break.

**Comment by dwayne-hart** [comment]
[Pull request 25](https://github.com/DFO-Ocean-Navigator/Navigator-Installer/pull/25) removes the provided version of Miniconda. The bin/configure.sh script removes any existing Miniconda version, then performs a fresh installation of Miniconda and the virtual environments that comprise the Ocean Navigator toolchain.

**Comment by jmunroe** [comment]
Good choice. I think this is the right solution (as matches what we are doing with npm).

Should the whole tools/miniconda directory be now removed from this repo? Also, did you want to pull Miniconda*.sh from a "official" url rather than including it within this repo?

**Comment by dwayne-hart** [comment]
[Pull request 26](https://github.com/DFO-Ocean-Navigator/Navigator-Installer/pull/26) brings it inline with how we are pulling in npm as @jmunroe  requested.

**Comment by dwayne-hart** [comment]
[Pull request 27](https://github.com/DFO-Ocean-Navigator/Navigator-Installer/pull/27) fully removes the tools/miniconda installation artifacts.

**Comment by jmunroe** [comment]
I had a need to go through the install instructions again this morning and was completely successful. Issue look to be resolved and may be closed. Thanks!
