### ISSUE TITLE
Update miniconda distro tarball

### ISSUE THREAD

**Issue by htmlboss** [DFO-Ocean-Navigator/Navigator-Installer#7]
With Geoff's update there are some new dependencies introduced. Right now we have `geoff.tar.bz2` sitting in `/data/installer_data` along with `minconda-distro.tar.bz2`. We need to replace the latter with the former and re-calculate the md5 hash.

**Comment by dwayne-hart** [comment]
All the files contained in the installer_data directory now have a corresponding .md5sum file.
